---
apiVersion: v1
kind: ConfigMap
metadata:
  name: maria-cm
data:
  DATABASE: "db"
  USER: "wp"
  PASSWORD: "123"
  ROOT_PASSWORD: "123"

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: maria-sts
  labels:
    app: maria-sts 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maria-sts

  # headless pvc
  serviceName: maria-pvc
  # pvc
  volumeClaimTemplates:
  - metadata:
      name: maria-100m-pvc
    spec:
      storageClassName: nfs-client
      accessModes: [ "ReadWriteMany" ]
      resources:
        requests:
          storage: 100Mi
 
  template:
    metadata:
      labels:
        app: maria-sts
    spec:
      containers:
      - name: mariadb
        image: mariadb:10
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: maria-100m-pvc
          mountPath: /var/lib/mysql
        envFrom:
        - prefix: 'MARIADB_'
          configMapRef:
            name: maria-cm
   
---
apiVersion: v1
kind: Service
metadata:
  name: maria-svc
  labels:
    app: maria-sts
spec:
  selector:
    app: maria-sts
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
