---
apiVersion: v1
kind: Pod
metadata:
  name: dev-pod
  namespace: dev-ns
  labels:
    name: dev-pod
spec:
  containers:
  - name: dev-pod
    image: nginx:alpine
    ports:
      - containerPort: 80
