---
apiVersion: v1
kind: Pod
metadata:
  name: ngx-probe-pod
  labels:
    name: ngx-probe-pod
spec:
  volumes:
    - name: ngx-conf-vol
      configMap:
        name: ngx-probe-cm
  containers:
  - name: ngx-probe-pod
    image: nginx:alpine
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    volumeMounts:
      - mountPath: /etc/nginx/conf.d
        name: ngx-conf-vol

    startupProbe:
      periodSeconds: 1
      exec:
        command: ["cat","/var/run/nginx.pid"]

    livenessProbe:
      periodSeconds: 10
      tcpSocket:
        port: 8080
        # port: 80

    readinessProbe:
      periodSeconds: 5
      httpGet:
        path: /ready
        port: 80
