---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ngx-probe-cm
data:
  default.conf: |
    server {
      listen 80;
      location = /ready {
        default_type text/plain;
        return 200 
        '
          srv : $server_addr:$server_port
          ver : $nginx_version
          host: $hostname
          uri : $request_method $host $request_uri
          date: $time_iso8601
        \n';
      }
    }
