---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-static-1g-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  nfs:
    path: /tmp/nfs/1g-pv
    server: master1
