---
apiVersion: v1
kind: Pod
metadata:
  name: busybox-pod
  labels:
    name: busybox-pod
    app: busybox-pod
spec:
  containers:
  - name: busybox-pod
    image: busybox
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    command: ["sleep","3600"]
  nodeSelector:
    checkbox: selected
