---
apiVersion: v1
kind: Pod
metadata:
  name: busybox-pod
  labels:
    name: busybox-pod
    app: busybox-pod
spec:
  containers:
  - name: busybox-pod
    image: busybox
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    command: ["sleep","3600"]
  nodeSelector:
    checkbox: selected

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: affinity
spec:
  replicas: 3  
  selector:
    matchLabels:
      app: affinity
  template:
    metadata:
      labels:
        app: affinity
    spec:
      containers:
      - name: affinity
        image: nginx:alpine
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 80

      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - busybox-pod
              topologyKey: kubernetes.io/hostname
