---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngx-hpa-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ngx-hpa-dep
  template:
    metadata:
      labels:
        app: ngx-hpa-dep
    spec:
      containers:
      - name: ngx-hpa-dep
        image: nginx:alpine
        resources:
          requests:
            memory: 10Mi
            cpu: 50m
          limits:
            memory: 20Mi
            cpu: 100m
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: ngx-hpa-svc
spec:
  selector:
    app: ngx-hpa-dep
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
