---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  labels:
    {{- include "mychart.app" . | indent 4 }}
  annotations:
      
data:
  course: {{ .Values.course }}
  {{- include "mychart.app" . | indent 2 }}
  salad: {{ .Values.global.salad }}
