apiVersion: v1
kind: Pod
metadata:
  name: volume-pod
  labels:
    name: volume-pod
spec:
  volumes:
    - name: cm-vol
      configMap:
        name: info
    - name: sec-vol
      secret:
        secretName: mysecret
  containers:
    - name: volume-pod
      image: busybox
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      command:
        - "/bin/sleep"
        - "300"
      volumeMounts:
        - mountPath: /tmp/cm-items
          name: cm-vol
        - mountPath: /tmp/sec-items
          name: sec-vol
